#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

xrandr --dpi 96 # Set DPI. User may want to use a larger number for larger screens.
xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources & xrdbpid=$!	# Uncomment to use Xresources colors/settings on startup

# Make cursor move faster
xset r rate 300 40

# Set random wallperper
WALLPAPER_DIR="${HOME}/.config/wallpaper"
feh --no-fehbg --bg-fill --randomize ${WALLPAPER_DIR}/*
#betterlockscreen --update ${WALLPAPER_DIR}
unset WALLPAPER_DIR

#autostart="mpd xcompmgr dunst unclutter pipewire"
autostart="mpd picom unclutter pipewire dunst"

for program in $autostart; do
  pidof -s "$program" || setsid -f "$program"
done >/dev/null 2>&1

# Ensure that xrdb has finished running before moving on to start the WM/DE.
[ -n "$xrdbpid" ] && wait "$xrdbpid"
