#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X


bspc config border_width         2
bspc config window_gap           8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a firefox desktop='^10'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Start polybar
$HOME/.config/polybar/launch.sh

# Set random wallperper
WALLPAPER_DIR="${HOME}/.config/wallpaper"
feh --no-fehbg --bg-fill --randomize ${WALLPAPER_DIR}/*
#betterlockscreen --update ${WALLPAPER_DIR}
unset WALLPAPER_DIR

# Change cursor from X to arrow
xsetroot -cursor_name left_ptr &



