-- Plugin manager
require 'plugins.packer'

-- Configure plugins
-- require 'plugins.lualine'
-- require 'plugins.cmp'
-- require 'plugins.lsp'
-- require 'plugins.telescope'
-- require 'plugins.treesitter'
-- require 'plugins.trouble_toggle'
-- require 'plugins.barbar'
-- require 'plugins.null_ls'
-- require 'plugins.nvim_dap'
-- require 'plugins.nvim_dap_ui'
-- require 'plugins.auto_pairs'
-- require 'plugins.gitsigns'
-- require 'plugins.comment'
-- require 'plugins.indent_blankline'
-- require 'plugins.nvim_tree'
-- require 'plugins.nvim_colorizer'